export const SET_USER_DETAILS = "SET_USER_DETAILS";
export const GET_LEADS = "GET_LEADS";
export const GET_REQUESTED_LEADS = "GET_REQUESTED_LEADS";
export const GET_ACCEPTED_LEADS = "GET_ACCEPTED_LEADS";
export const GET_REJECTED_LEADS = "GET_REJECTED_LEADS";
